server:
  port: 9000

spring:
  application:
    name: bunjang

  datasource:
    platform: mysql
    url: jdbc:mysql://bunjang.czzbubqkgnqz.ap-northeast-2.rds.amazonaws.com/BunJang?autoReconnect=true # 변경해주세요
    username: admin
    password: 123456780!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전